### ISSUE TITLE
Alternate-contacts: Bug in latest jsonschema package

### ISSUE THREAD

**Issue by be-aws-architect** [aws-samples/aft-workshop-sample#15]
Hello,

While deploying the **aft-alternate-contacts** solution I ran into an issue in the **validate-alternate-contacts** Lambda function:

`
[ERROR] Runtime.ImportModuleError: Unable to import module 'validate-alternate-contacts': No module named 'rpds.rpds' Traceback (most recent call last):
`

This is a known problem in the **jsconschema** package. installed version was 4.19.X. This is a known issue by the provider: https://github.com/python-jsonschema/jsonschema/issues/1117

Setting the version to **4.17.3** in the **requirements.txt** and redeploying solved the issue.

`jsonschema==4.17.3`

Can you set the version constraint in the module until the issue is fixed by the provider?

**Comment by Chainshark** [comment]
On top of that, you should either remove the concurrency limit or increase it, as it serves no function. On my second testrun, my function failed because there was another one running.. I ran it on two accounts.

**Comment by wellsiau-aws** [comment]
concurrency issues related to #14 . Since the API call is made from AFT management account, we are are limited to the quota at AFT account level.
