### ISSUE TITLE
error in aft-workshop-sample

### ISSUE THREAD

**Issue by maricat0210** [aws-samples/aft-workshop-sample#16]
when executing step4 [(Execute the bash script to launch the Cloud9. Change the placeholder {{CT-HOME-REGION}} with your AWS Control Tower home region (AWS region where AWS Control Tower is deployed).)](https://catalog.workshops.aws/control-tower/en-US/customization/aft/prerequisites#prep-terraform-environment-for-aft-deployment) In the prerequisites section of aft-workshop-sample, the following error occurs.

│ Error: Missing required argument
│ 
│   on main.tf line 34, in resource "aws_cloud9_environment_ec2" "cloud9-aft":
│   34: resource "aws_cloud9_environment_ec2" "cloud9-aft" {
│ 
│ The argument "image_id" is required, but no definition was found.

**Comment by jarrettj** [comment]
Encountered the same issue :|

They must of deleted the image.

**Comment by roguen** [comment]
The issue is in main.tf
Add a new line 38 with the following

  image_id      = "amazonlinux-2023-x86_64"

And it will run as expected.  This was a new property added to the API call at the end of last year.

**Comment by wellsiau-aws** [comment]
PR #17 should resolve this now, let us know if you are still encountering problem , thank you.
