### ISSUE TITLE
import jsonschema fails for aft-alternate-contacts-validate Lambda

### ISSUE THREAD

**Issue by schroehe** [aws-samples/aft-workshop-sample#18]
State machine execution breaks with the following error:

[ERROR] Runtime.ImportModuleError: Unable to import module 'validate-alternate-contacts': No module named 'jsonschema'
Traceback (most recent call last):

apparently the import jsonschema does not work.

**Comment by wellsiau-aws** [comment]
@schroehe , thanks for reporting the issue.

did you tried to run `make build` prior to pushing the `aft-alternate-contacts` to the pipeline?

if you look at the steps described [here](https://catalog.workshops.aws/control-tower/en-US/customization/aft/customizations/update-repo), it requires you to run `make build` 

Please let me know if the issue persisted even after you run `make build`
