### ISSUE TITLE
Error: The argument "image_id" is required, but no definition was found.

### ISSUE THREAD

**Issue by schwinbp** [aws-samples/aft-workshop-sample#19]
I am trying to run the cloud9.sh script in Cloud9 for my aft account. Everything seems to install fine until the end I am getting this error below. How can I get past this error? I am not able to acutally view the code in this repo for some reason. 

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Missing required argument
│ 
│   on main.tf line 34, in resource "aws_cloud9_environment_ec2" "cloud9-aft":
│   34: resource "aws_cloud9_environment_ec2" "cloud9-aft" {
│ 
│ The argument "image_id" is required, but no definition was found.

Brian

**Comment by wellsiau-aws** [comment]
relates to #16

**Comment by wellsiau-aws** [comment]
PR #17 resolves this issue, please let me know if it still causing issue for you
