### ISSUE TITLE
AWS Control Tower Workshop broken link

### ISSUE THREAD

**Issue by dheepansn** [aws-samples/aft-workshop-sample#25]
There are a few broken links on the documentation page - https://github.com/aws-samples/aft-workshop-sample.

I want to thank you for creating such a great Control Tower Documentation. However, all of a sudden the link is broken, and not able to access it anymore.  

Broken Link:
https://controltower.aws-management.tools/automation/
https://controltower.aws-management.tools/

**Comment by aaarcr** [comment]
Created pull request to address #26

**Comment by matheuslra** [comment]
Merged
