### ISSUE TITLE
Terraform version 4 has introduced breaking changes

### ISSUE THREAD

**Issue by shannoncolavita** [aws-samples/aft-workshop-sample#6]
Ref: https://github.com/hashicorp/terraform-provider-aws/issues/20592
aws_subnet_ids no longer exists

**Comment by wellsiau-aws** [comment]
thanks for reporting this, I am taking a look

**Comment by wellsiau-aws** [comment]
thanks again for reporting this, #8 should fix this problem now. I did run a quick test to confirm on my local environment.
